### ISSUE TITLE
[Enhancement] Add favorite tags buttons

### ISSUE THREAD

**Issue by 0neW0rld** [ciccabanana/e-hentai-helper-suite#10]
Hi, I was wondering if you could please add a feature that lets users add their favorite tags as buttons under the search bar? This would make our most used tags easier to add to the search.

Here's an example from another script:
![a3](https://github.com/ciccabanana/e-hentai-helper-suite/assets/120766951/dda3f6b4-af78-47a9-96c6-ffd50158438c)

Unfortunately, due to the implementation of the script shown in the example it isn't compatible with e-hentai-helper-suite.

Thanks for sharing this script by the way, it's extremely helpful!

**Comment by ciccabanana** [comment]
Hello, I was working about a this feature for several months together with the support of qualifiers (at least the tag qualifier)
I almost finished, I have only some bug to resolve and i will push the update.

**Comment by ciccabanana** [comment]
I wonder if a maximum of 25 favorite will be sufficient, what do you think @0neW0rld?

**Comment by 0neW0rld** [comment]
25 is more than enough for my needs, thank you so much for working on this!

**Comment by bropines** [comment]
It's about time I realized that. When's the update?

**Comment by ciccabanana** [comment]
I hope to push the update at least by the end of next week.
I have only 1 bug left and is about favorite/bookmarks and the Qualifiers.
Removed the bug, at least, I need to test if the script load and works on Firefox and with Greasemonkey and Violentmonkey

🤞 I hope that all works fine 🤞

I wrote a lot of new code and changed a lot for these new features. Git stats:
`1 file changed, 963 insertions(+), 221 deletions(-)`

**Comment by bropines** [comment]
Good luck

**Comment by ciccabanana** [comment]
It's done. I hope that all works fine. If you can give me a feedback or an opinions, here or on the forum, will be appreciated :smile:

**Comment by 0neW0rld** [comment]
@ciccabanana thanks for all your hard work on this! It works perfectly and I think your implementation is better than the example I provided.
