### ISSUE TITLE
0.2 not working, with tampermonkey/violentmonkey on firefox/chrome

### ISSUE THREAD

**Issue by Jerrk** [ciccabanana/e-hentai-helper-suite#7]
tampermonkey and violentmokney give these console errors on both chrome and firefox respectively:

`Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules (at userscript.html?name=Tags-Auto-Complete.user.js&id=e45c4d55-cd12-4795-afd7-bf5f40c5021b:1320:5)`

`[Violentmonkey][Tags Auto Complete] SyntaxError: await is only valid in async functions, async generators and modules`

pointing to this line in the code https://github.com/ciccabanana/e-hentai-helper-suite/blob/master/e-hentai-tags-helper.user.js#L1249

Neither browser shows the cogwheel in the searchbar or shows any autocompletes when starting to type, neither on the frontpage or in favorites. tried e-hentai.org as well both logged in and logged out, no change.

**Comment by ciccabanana** [comment]
The issue seam fixed for Tampermonkey, but other bug appeared on Violentmonkey.

**Comment by ciccabanana** [comment]
Ok, this time should be all fixed.
I have tested it on Tampermonkey, Violentmonkey and Greasemonkey on both site.
@Jerrk if you can test it tell me if found some other problem. I leave this issue open for now.

**Comment by Jerrk** [comment]
Works for me with no issues, thanks for the quick fix!
